### PR TITLE
Feature feature selection

### PR DESCRIPTION
**Pull request by parva-jain**
Partial #30

Added a Feature Selection technique called ChiSquare and its test script.

### CODE REVIEW

**Comment by parva-jain** [comment]
There are two many PEP 8 issues, will correct them by tommorrow.

**Comment by parva-jain** [comment]
Hey @sidhu1012, the files I have pushed have shown no error when tested with flake8 but giving build errors here, what's the reason?

**Comment by sidhu1012** [comment]
> Hey @sidhu1012, the files I have pushed have shown no error when tested with flake8 but giving build errors here, what's the reason?

Ik , I'll try to fix it tomorrow.

**Comment by sidhu1012** [comment]
@parva-jain Travis has been fixed , use `git pull https://github.com/Dacience/DataScientist.git` then push again.

**Comment by parva-jain** [comment]
@sidhu1012 now what's wrong?

**Pull request merged**
