### PR TITLE
(gradient_boosting regressor + test cases) along with change in typo in lasso.py

### LINKED ISSUE #1: Make Regression modules
Implement all regression models present here under suitable sub modules :-
https://scikit-learn.org/stable/modules/classes.html#module-sklearn.linear_model

### LINKED ISSUE #52: Typo in the comment in line 12 of lasso.py under linear models of regression module (use of 2 "for")
datascientist/model/regression/skl/linear_model/lasso.py

### PR DESCRIPTION
**Pull request by shreyaspj20**
Fixes #52
Fixes #53
Partial fix #1

### CODE REVIEW

**Comment by shreyaspj20** [comment]
I have all test cases passed on the local machine but Travis CI check isn't passed. Can I get some help regarding changes to be made?

**Comment by sidhu1012** [comment]
> I have all test cases passed on the local machine but Travis CI check isn't passed. Can I get some help regarding changes to be made?

Yes this problem is happening for a while now , till it's resolved please update the test cases with what Travis expect.

I'll soon replace Travis with github actions, but till then please cope with it.

**Comment by shreyaspj20** [comment]
Sure. Thanks for the suggestion.

**Comment by sidhu1012** [comment]
LGTM!!

**Pull request merged**
