### PR TITLE
Added the following Nearest Neighbor Algorithms and their tests:

### PR DESCRIPTION
**Pull request by anishkabhatia**
- KD Tree and its test
- KNeighbors Classifier and its test
- Local Outlier Factor and its test
- Kernel Density and its test
- Radius Neighbors Classifier and its test
- Nearest Centroid and its test
- Nearest Neighbor and its test
- Neighborhood Components Analysis and its test

### CODE REVIEW

**Comment by anishkabhatia** [comment]
> @sidhu1012 I have a doubt, will KNeighbors Transformer, KNeighbors Regressor, Radius Neighbors Transformer and Radius Neighbors Regressor come under classification only?

@sidhu1012 Could you help me so I can resume working further?

**Comment by sidhu1012** [comment]
> > @sidhu1012 I have a doubt, will KNeighbors Transformer, KNeighbors Regressor, Radius Neighbors Transformer and Radius Neighbors Regressor come under classification only?
> 
> @sidhu1012 Could you help me so I can resume working further?

No they don't come under `classification` . You can read more [here](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.neighbors).

**Comment by anishkabhatia** [comment]
> > > @sidhu1012 I have a doubt, will KNeighbors Transformer, KNeighbors Regressor, Radius Neighbors Transformer and Radius Neighbors Regressor come under classification only?
> > 
> > 
> > @sidhu1012 Could you help me so I can resume working further?
> 
> No they don't come under `classification` . You can read more [here](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.neighbors).

Okay, Thanks. Also, Please review these files and let me know in case of any changes

**Comment by sidhu1012** [comment]
@anishkabhatia Are all models that you added, classifiers?

**Comment by anishkabhatia** [comment]
> @anishkabhatia Are all models that you added, classifiers?

@sidhu1012 Yes, I didn't add the regression and transformation models. These are all classifiers

**Pull request merged**
