### PR TITLE
Create Code_of_conduct.md

### PR DESCRIPTION
**Pull request by NEERAJAP2001**
1.Added Create Code_of_conduct.md 

2.This pull request is a part of NJACK Winter of Code so please merge this after 1 Dec 2020 so that it gets counted.

3.Solves issue #39

### CODE REVIEW

**Comment by Pranav016** [comment]
Sorry Sir, this issue was assigned and I had spent a couple of hours working on it and this pull request degrades the hours I spent. Please before working on any issue, check if it has been assigned to anyone and follow rules of NJACK.

**Comment by sidhu1012** [comment]
This issue is already being worked on #42

**Comment by NEERAJAP2001** [comment]
My Bad I thought you were busy with the other issues,
Thanks

**Comment by sidhu1012** [comment]
> My Bad I thought you were busy with the other issues,
> Thanks
> 

You can work on other issues there are plenty!

**Pull request closed without merging**
