### PR TITLE
Added Ball Tree module and it's test

### PR DESCRIPTION
**Pull request by anishkabhatia**

### CODE REVIEW

**Comment by anishkabhatia** [comment]
Can anyone help me out as why did the check fail?

**Comment by sidhu1012** [comment]
> Can anyone help me out as why did the check fail?
> 

Because you didn't install DataSceintist in development mode.


Use `pip install -e .` in terminal and run your script and push again.

**Comment by anishkabhatia** [comment]
> > Can anyone help me out as why did the check fail?
> 
> Because you didn't install DataSceintist in development mode.
> 
> Use `pip install -e .` in terminal and run your script and push again.

image
Show's this error

**Comment by anishkabhatia** [comment]
> > > Can anyone help me out as why did the check fail?
> > 
> > 
> > Because you didn't install DataSceintist in development mode.
> > Use `pip install -e .` in terminal and run your script and push again.
> 
> image
> @sidhu1012 Show's this error

Solved it.

**Comment by anishkabhatia** [comment]
> > Can anyone help me out as why did the check fail?
> 
> Because you didn't install DataSceintist in development mode.
> 
> Use `pip install -e .` in terminal and run your script and push again.

How do I run my script again? I have added DataScientist in the development mode

**Comment by sidhu1012** [comment]
> > > Can anyone help me out as why did the check fail?
> > 
> > Because you didn't install DataSceintist in development mode.
> > 
> > Use `pip install -e .` in terminal and run your script and push again.
> 
> How do I run my script again? I have added DataScientist in the development mode

First run on your system and if it's fine add a new line anywhere and push again

**Comment by anishkabhatia** [comment]
> > > > Can anyone help me out as why did the check fail?
> > > 
> > > 
> > > Because you didn't install DataSceintist in development mode.
> > > Use `pip install -e .` in terminal and run your script and push again.
> > 
> > 
> > How do I run my script again? I have added Data Scientist in the development mode
> 
> First run on your system and if it's fine add a new line anywhere and push again

The check is failing still. The setup file needs to be changed in the main branch

**Comment by sidhu1012** [comment]
@anishkabhatia The failing tests has been solved , please place your KNN file in  classification/linear_model

**Pull request closed without merging**
