### PR TITLE
Added logo for Dacience organization

### PR DESCRIPTION
**Pull request by Pranav016**
## This PR has been made under NWoC
Issue solved-
#90 
Took a while to design this logo. Hope you like it! 😄 

Screenshot preview of the original logo-

LOGO1
LOGO2
LOGO3

### CODE REVIEW

**Comment by sidhu1012** [comment]
Any other option for logo? It's good but if you could possibly give a couple of options?

**Comment by Pranav016** [comment]
> Any other option for logo? It's good but if you could possibly give a couple of options?

Sure, I'll work on more. Will add tomorrow morning..

**Comment by Pranav016** [comment]
> > Any other option for logo? It's good but if you could possibly give a couple of options?
> 
> Sure, I'll work on more. Will add tomorrow morning..

Designed a couple more Logo's. Please give good points for this, took a lot of time since I designed these myself 😄

**Comment by sidhu1012** [comment]
The first one looks good, go with it.

**Comment by Pranav016** [comment]
> The first one looks good, go with it.

You can merge it, and keep the logo's. All the logo's will be there in logo's folder..
Should I add them to the readme?

**Comment by sidhu1012** [comment]
No, I'll merge it!

**Comment by Pranav016** [comment]
> No, I'll merge it!

Good to merge now? 😀

**Pull request merged**
