### PR TITLE
Data Analysis

### LINKED ISSUE #37: Make sub-module Data Analysis
Make a sub module Data analysis which takes input inform of array or data frame and returns relation between every column, missing values etc , with relevant plots.

### PR DESCRIPTION
**Pull request by kritikaparmar-programmer**
Fixes #37 

Description: 
Added .py file for DataAnalysis

### CODE REVIEW

**Comment by kritikaparmar-programmer** [comment]
Hey, @sidhu1012 I'd make a function for eda which takes the input of a dataframe and return plots and values like missing values and correlation of every column. Kindly take a look.

**Comment by sidhu1012** [comment]
> Hey, @sidhu1012 I'd make a function for eda which takes the input of a dataframe and return plots and values like missing values and correlation of every column. Kindly take a look.

Can you please show me an example output.

**Comment by kritikaparmar-programmer** [comment]
Hey @sidhu1012 I've added a .ipynb file showing an example, Kindly take a look.

**Comment by sidhu1012** [comment]
Dont add `.ipynb` just share a photo(probably ss) of how the output would look.

**Comment by sidhu1012** [comment]
@kritikaparmar-programmer Are you interested in finishing your work?

**Comment by kritikaparmar-programmer** [comment]
> @kritikaparmar-programmer Are you interested in finishing your work?

Yes @sidhu1012 I'll complete it, actually, I'm having exams right now, which is causing the delay, I'll provide you ss of solution.

**Comment by kritikaparmar-programmer** [comment]
Hey @sidhu1012 I looked at my code again, it is working fine in jupyter notebook but not in cmd. Talking about the output ss, it is clearly seen in the jupyter notebook. Please suggest any changes if you want. I'm active now.

**Comment by sidhu1012** [comment]
@kritikaparmar-programmer Remove python notebook from PR and send sa of output on jupyter.

**Comment by kritikaparmar-programmer** [comment]
ss1
ss2
ss3
ss4
ss5
@sidhu1012

**Pull request merged**
